// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: inventory.sql

package db

import (
	"context"
)

const addInventory = `-- name: AddInventory :exec
INSERT INTO Inventories (
  ProductID,
  Quantity
) VALUES (
  ?, ?
)
`

type AddInventoryParams struct {
	Productid string `json:"productid"`
	Quantity  int32  `json:"quantity"`
}

func (q *Queries) AddInventory(ctx context.Context, arg AddInventoryParams) error {
	_, err := q.db.ExecContext(ctx, addInventory, arg.Productid, arg.Quantity)
	return err
}

const deleteInventory = `-- name: DeleteInventory :exec
DELETE FROM Inventories
WHERE ID = ?
`

func (q *Queries) DeleteInventory(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteInventory, id)
	return err
}

const getInventory = `-- name: GetInventory :one
SELECT id, productid, quantity, created, modified FROM Inventories
WHERE ID = ?
LIMIT 1
`

func (q *Queries) GetInventory(ctx context.Context, id string) (Inventory, error) {
	row := q.db.QueryRowContext(ctx, getInventory, id)
	var i Inventory
	err := row.Scan(
		&i.ID,
		&i.Productid,
		&i.Quantity,
		&i.Created,
		&i.Modified,
	)
	return i, err
}

const getListInventories = `-- name: GetListInventories :many
SELECT id, productid, quantity, created, modified FROM Inventories
LIMIT ? OFFSET ?
`

type GetListInventoriesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetListInventories(ctx context.Context, arg GetListInventoriesParams) ([]Inventory, error) {
	rows, err := q.db.QueryContext(ctx, getListInventories, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Inventory{}
	for rows.Next() {
		var i Inventory
		if err := rows.Scan(
			&i.ID,
			&i.Productid,
			&i.Quantity,
			&i.Created,
			&i.Modified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInventoryQuantity = `-- name: UpdateInventoryQuantity :exec
UPDATE Inventories
SET Quantity = Quantity + ?,
    Modified = current_timestamp
WHERE ProductID = ?
`

type UpdateInventoryQuantityParams struct {
	Quantity  int32  `json:"quantity"`
	Productid string `json:"productid"`
}

func (q *Queries) UpdateInventoryQuantity(ctx context.Context, arg UpdateInventoryQuantityParams) error {
	_, err := q.db.ExecContext(ctx, updateInventoryQuantity, arg.Quantity, arg.Productid)
	return err
}
