// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"
)

type Customer struct {
	ID           string    `json:"id"`
	Firstname    string    `json:"firstname"`
	Lastname     string    `json:"lastname"`
	Gender       string    `json:"gender"`
	Tel          string    `json:"tel"`
	EmailAddress string    `json:"email_address"`
	Created      time.Time `json:"created"`
	Modified     time.Time `json:"modified"`
}

type Inventory struct {
	ID        string    `json:"id"`
	Productid string    `json:"productid"`
	Quantity  int32     `json:"quantity"`
	Created   time.Time `json:"created"`
	Modified  time.Time `json:"modified"`
}

type Order struct {
	ID         string    `json:"id"`
	Customerid string    `json:"customerid"`
	Productid  string    `json:"productid"`
	Quantity   int32     `json:"quantity"`
	Amount     float64   `json:"amount"`
	Created    time.Time `json:"created"`
	Modified   time.Time `json:"modified"`
}

type Product struct {
	ID       string    `json:"id"`
	Name     string    `json:"name"`
	Price    float64   `json:"price"`
	Created  time.Time `json:"created"`
	Modified time.Time `json:"modified"`
}
