// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	AddCustomer(ctx context.Context, arg AddCustomerParams) error
	AddInventory(ctx context.Context, arg AddInventoryParams) error
	AddOrder(ctx context.Context, arg AddOrderParams) error
	AddProduct(ctx context.Context, arg AddProductParams) error
	DeleteCustomer(ctx context.Context, id string) error
	DeleteInventory(ctx context.Context, id string) error
	DeleteOrder(ctx context.Context, id string) error
	DeleteProduct(ctx context.Context, id string) error
	GetCustomer(ctx context.Context, id string) (Customer, error)
	GetInventory(ctx context.Context, id string) (GetInventoryRow, error)
	GetListCustomers(ctx context.Context, arg GetListCustomersParams) ([]Customer, error)
	GetListInventories(ctx context.Context, arg GetListInventoriesParams) ([]GetListInventoriesRow, error)
	GetListOrders(ctx context.Context, arg GetListOrdersParams) ([]GetListOrdersRow, error)
	GetListProducts(ctx context.Context, arg GetListProductsParams) ([]Product, error)
	GetOrder(ctx context.Context, id string) (GetOrderRow, error)
	GetProduct(ctx context.Context, id string) (Product, error)
	UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) error
	UpdateInventoryQuantity(ctx context.Context, arg UpdateInventoryQuantityParams) error
	UpdateProduct(ctx context.Context, arg UpdateProductParams) error
}

var _ Querier = (*Queries)(nil)
